### ISSUE TITLE
Off centre map

### ISSUE THREAD

**Issue by Lextuga007** [traffordDataLab/trafford_covid-19#1]
The formatting  of the Confirmed cases by MSOA map is slightly off centre and can't be corrected when using Edge - Chrome works fine.

**Comment by itsozz** [comment]
Apologies for this issue taking a while.  As a temporary solution I have removed the boundary snap which prevents the map from being panned/dragged. I'm hoping to find a better solution long-term, however at least it can now be manually moved into view if this issue occurs.

**Comment by Lextuga007** [comment]
Thanks for the update and workaround. Much appreciated.
